keys:
  - &mason_xpsonix age1w4gpvqfdw2w7ly0fjlcaddxlvt3mwd0hvp3rhvk4jtd5m2cmsp4segcmej
  - &host_xpsonix age1sj3axmvypjme2f9m7csxehahj78chnek6dhrhhlv4hqjd4lgd5lq6sehmk
  - &mason_masonmac age1laa24tfw3yf9sms55ydw8h437h7ksyt4alwnsjg3z5569tlc0gmq2ceyvt
  - &host_worldgov age144x7l63e0c5krtdsdc7f9gfqf2yettftadkcsfzh2kw3x58wqylqh3xfvk

creation_rules:
  - path_regex: secrets/worldgov\.yaml$
    key_groups:
      - age:
          - *mason_xpsonix
          - *mason_masonmac
          - *host_xpsonix
          - *host_worldgov
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *mason_xpsonix
          - *mason_masonmac
          - *host_xpsonix
