keys:
  - &mason_xpsonix age1w4gpvqfdw2w7ly0fjlcaddxlvt3mwd0hvp3rhvk4jtd5m2cmsp4segcmej
  - &host_xpsonix age1sj3axmvypjme2f9m7csxehahj78chnek6dhrhhlv4hqjd4lgd5lq6sehmk

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *mason_xpsonix
          - *host_xpsonix
