super_secret: ENC[AES256_GCM,data:d6BxzlgWQwVPbGF/oxtO5ks=,iv:U3W7lVBSTQuSpmSoNICdaJMsW8ni+WswTN9EWthB+Sc=,tag:3zCCtKdjyAW/o2DgXRXQKg==,type:str]
sops:
  age:
    - recipient: age1w4gpvqfdw2w7ly0fjlcaddxlvt3mwd0hvp3rhvk4jtd5m2cmsp4segcmej
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTR21WZzMvem5JVHZmTUY2
        K2pjYkdpNUViZXNDQy9Tc3hyZmdMdlg0Y0VZCmZCUGdnMGxCbHJ4SU90bFRhdmNW
        cjhZVFdmU1hyRXhVMmcxdHJmTkdzOWcKLS0tIHpTU09JcmdnVStuUmwyd0IrRTNM
        bVhGYkxQUVFmYzBrVmhUbHZpMzdzdlUKFjSP/f9cBIOIqef2j7LG72+kx6dNR1qy
        tXD8fOLKBwabrv5g9aonyNPYyMFC5E5K8oGsI3dc5VAXN+c+KJ00CA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1sj3axmvypjme2f9m7csxehahj78chnek6dhrhhlv4hqjd4lgd5lq6sehmk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNlptbnMvSGVIK0hDQzF0
        ZmNhV2JKb3pWU2REQXhxQlA5NzIzRkVHS2dvCm1HWDhsdXhzaXMrL3I2YjNuNkxN
        SE4rdXBxaERNNXJUaTRBSVpaRi8zR28KLS0tIHlTa2R3enJMWWxpVVlDeDF4NVlG
        Z3Rla2drbU85bVdPRk5JdS8vMUNaUGMKh0RuFbPLj1emNnOHuTf0cIs1pTK9wWFp
        mgXjfqYW2Wkoon6av+58lu3wjGlzWqYMlrVeoe3SV/QSKJO1xLkjxg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-13T15:17:41Z"
  mac: ENC[AES256_GCM,data:7nUHypWTc4szgpzQ9LNOSBP/cKU90nPBK2m3FGyMedpDWw7au2J4YP+fhVnqvw9HoaUTt9yAuwR2Gpl9sDJ/MLspTxJFD+Waluy/9RQVIeJj3byKdTUIstrSSlcv5hbohbS2EtKhnBk7hE4QKcskDfgaDK9c5QctXw8/aHtvuP4=,iv:dsH3uquBAtYj/p5yLjkQzHYY7jfrpe2rgEYr0Jddx2g=,tag:2ewP1mhsZ4AE/R3EUm9QJg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
