personalEmail: ENC[AES256_GCM,data:vViNQtAVbiX6KgOU4UTJKcWP7zE=,iv:d7I+4RVsA2jnMpoQfvFOsXlFpqc7JCf4MBcaKMYnco8=,tag:n4r/rTBAADK3DOujjZ/CZw==,type:str]
sops:
    age:
        - recipient: age1w4gpvqfdw2w7ly0fjlcaddxlvt3mwd0hvp3rhvk4jtd5m2cmsp4segcmej
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Z2IvNzczS0x2bnJhT2Vv
            eXYwQmFaVUlxOG5xd2FDQkhmY2RGQ3FBWVZJClNNaEMvMG1KUFZPRm5FdWxXUUJn
            am1PNGZHQXJOSmlRRVhNcG9ueDFFVm8KLS0tIFAvMlF5WW90NW80RFJJMTVrY3E5
            OHY2Wk54bkQ5Rno0c0hvMGJMTStUYzgKaWxoKjihEiIcieu9qcinngAumj6//c8q
            U4WO+awN1PeXvmf34NpTHBdgRINUD98fLyR2eo3rIL9eOn25TRr1ww==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sj3axmvypjme2f9m7csxehahj78chnek6dhrhhlv4hqjd4lgd5lq6sehmk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MEpEbDM1TkdSZUVLa2NF
            dWpSMkxRMWpWVTVhV0Znb0lsZVEweWZ6UVZjCkhWY05jSDVuODdnOFVpVSs4R2ds
            M09DNzZRNjh0bmxVa3drUXV3Z0JSSEUKLS0tIEZkSG9ucmlUOE1HbFhSM002L1NN
            N1NMNEJzM056OXdPR3pYUHNGS2ptN2sKj/s+4bsXyi51NVSCu/h7sDYEYtY3h3dU
            j6lPKkbck+haIoftQP6zada8DPDdkJ1h/HV26DLf0eFe/C3bMeaOiQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1laa24tfw3yf9sms55ydw8h437h7ksyt4alwnsjg3z5569tlc0gmq2ceyvt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NkVKbTdQTFJMUXlhMEV1
            WXppaERJaXovc01kWFBVNE5MRTExY29odXlJCmJvQVo4TFQ2em1lUjhtdkxZQkNB
            cHNuazhVZTV5eVE4ZFRtdk5mcVZZZW8KLS0tIGRSSkRRT25UeDhDbkM3V1ZucjZy
            RmFBU2xZZUNMVlo0d1NtZEt4MFU5K3cKJiYFLY8f0RNsI2Arz+bl6wkSF6CVuK8i
            lWQosu2koqx5MN5sRWOYzWazf6+2Cb0L1EtvgBz3qDJX0XZEDLG//w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T23:40:02Z"
    mac: ENC[AES256_GCM,data:dqtWuyj/Zks6tY83qiaT15mpErBmq/60xV71jko5frNRMwY/Af9kmPJ30P9Gc+lETouHCVwvslTGrELXv84eE+UFneDaLsb1s2kSJeONsHBTCjHdS2sw+8dJ1URkIh3U71YZPlKMnYvxLWOR7/k9wbzaWziLXo5Cm/lFe3b9++o=,iv:tzxcg6btnZ/amwNjzJLC1NoGrfK0iA6uF6gVBXBqTvw=,tag:0dams2nlq5XbD7nQ52bcJg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
