super_secret: ENC[AES256_GCM,data:d6BxzlgWQwVPbGF/oxtO5ks=,iv:U3W7lVBSTQuSpmSoNICdaJMsW8ni+WswTN9EWthB+Sc=,tag:3zCCtKdjyAW/o2DgXRXQKg==,type:str]
sops:
    age:
        - recipient: age1w4gpvqfdw2w7ly0fjlcaddxlvt3mwd0hvp3rhvk4jtd5m2cmsp4segcmej
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Z2IvNzczS0x2bnJhT2Vv
            eXYwQmFaVUlxOG5xd2FDQkhmY2RGQ3FBWVZJClNNaEMvMG1KUFZPRm5FdWxXUUJn
            am1PNGZHQXJOSmlRRVhNcG9ueDFFVm8KLS0tIFAvMlF5WW90NW80RFJJMTVrY3E5
            OHY2Wk54bkQ5Rno0c0hvMGJMTStUYzgKaWxoKjihEiIcieu9qcinngAumj6//c8q
            U4WO+awN1PeXvmf34NpTHBdgRINUD98fLyR2eo3rIL9eOn25TRr1ww==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sj3axmvypjme2f9m7csxehahj78chnek6dhrhhlv4hqjd4lgd5lq6sehmk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MEpEbDM1TkdSZUVLa2NF
            dWpSMkxRMWpWVTVhV0Znb0lsZVEweWZ6UVZjCkhWY05jSDVuODdnOFVpVSs4R2ds
            M09DNzZRNjh0bmxVa3drUXV3Z0JSSEUKLS0tIEZkSG9ucmlUOE1HbFhSM002L1NN
            N1NMNEJzM056OXdPR3pYUHNGS2ptN2sKj/s+4bsXyi51NVSCu/h7sDYEYtY3h3dU
            j6lPKkbck+haIoftQP6zada8DPDdkJ1h/HV26DLf0eFe/C3bMeaOiQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1laa24tfw3yf9sms55ydw8h437h7ksyt4alwnsjg3z5569tlc0gmq2ceyvt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NkVKbTdQTFJMUXlhMEV1
            WXppaERJaXovc01kWFBVNE5MRTExY29odXlJCmJvQVo4TFQ2em1lUjhtdkxZQkNB
            cHNuazhVZTV5eVE4ZFRtdk5mcVZZZW8KLS0tIGRSSkRRT25UeDhDbkM3V1ZucjZy
            RmFBU2xZZUNMVlo0d1NtZEt4MFU5K3cKJiYFLY8f0RNsI2Arz+bl6wkSF6CVuK8i
            lWQosu2koqx5MN5sRWOYzWazf6+2Cb0L1EtvgBz3qDJX0XZEDLG//w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T15:17:41Z"
    mac: ENC[AES256_GCM,data:7nUHypWTc4szgpzQ9LNOSBP/cKU90nPBK2m3FGyMedpDWw7au2J4YP+fhVnqvw9HoaUTt9yAuwR2Gpl9sDJ/MLspTxJFD+Waluy/9RQVIeJj3byKdTUIstrSSlcv5hbohbS2EtKhnBk7hE4QKcskDfgaDK9c5QctXw8/aHtvuP4=,iv:dsH3uquBAtYj/p5yLjkQzHYY7jfrpe2rgEYr0Jddx2g=,tag:2ewP1mhsZ4AE/R3EUm9QJg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
