#ENC[AES256_GCM,data:d1JbYXyX1Bwrxv8cW6YDAhEEqSnKAs7px8toJ9pqAQY1CpCFFRWP6QBh4ahX5SQO5P/uGUYGZxVdRSmCdEtjdu4vs8j/qZSSkqlw71n6aVhGvICmSsy0Z3ySNwE2iGaI0d/rgL/0thfft2uddlV23XQ=,iv:PItrb8P+31Fld9u4s+ZBJXrnABwMIh4/y8FyX5gIQFU=,tag:knlCQ9fEjmrof1xRoL/3TA==,type:comment]
nordAccessToken: ENC[AES256_GCM,data:dPz6RWasjCfnTVN3/1oCGb6l64C9B5A/mr6AUMFX0/4V31tqwDRvzqPEpIsuEbu77tDPZuOZwQdEa9800u4a0g==,iv:nInn8RkaAlyLRtXm8dzCMHHnzkWXgmknxboGha8ZA1A=,tag:d5RngciwaAskfwDdm5qGcw==,type:str]
#ENC[AES256_GCM,data:SAdJeG2Y+hJZeUMLHj53uKAB5b39FU8LuI9Loj0P6hVnzWWOlVx8m23ehAIrK3nMsMxkfV25B0DvRjNYiGQE2+TENwbrYD9Ok04YwIU+LBkwpHEqU88=,iv:+16HCXgY7kUNBoWeKmqXoA4131yruxgggCaFk3ya/EU=,tag:YQ5jX0dWgPQ5TTFImhL6nQ==,type:comment]
#
#ENC[AES256_GCM,data:+J2qS52a/cLnnmOJrNWulFRCFF6I1XgMyrNgYZh1QRbALKztUu1WWq+DqoVtsRzpOvnExpLQWZ36uC6f4LazQG13iJmUUwhN5NG9ee/1I0n5v8ZUcx/16wZfWp+L9f6/eWVrPi2a30Ry+YZSS+JV3zA+z198yj3KGa5hEGw5Cp7AqtOUpA==,iv:XPNxb2Hy32jKkKoaXTwfp5pPjmgy2EJriyGAQKHBlzg=,tag:aRt3ZvaFLMAOPzqZeoT8Bg==,type:comment]
#ENC[AES256_GCM,data:oK4eb++WXweoSKHTMU54TLXaFx1IUVZEcNz09LSktLFIsre9e75yv2L5UFEWLqXJM7OJwK+NbjGhJ3apQLSa5cwG0DnNS8s+qCys/ROMneJBBT8C8qSnDm0KFB6hNadcYQn0ksC8Yq2yi2Jt4tA2x/2VfqID2pxVR8Uj6Cmgi+11IsIVbl2FfPBBxpLYwSxFaYrFRdLDgKb4j3EDFxGZqekhrMfY5abwXEXBHHox0A4=,iv:L39YeQTacfMqVRi+6D+Pfakkdlvy8XQuLaAMtQ1zYkQ=,tag:9s5XQJPD+87jnSi9nC9yyw==,type:comment]
#
#ENC[AES256_GCM,data:PB9JkWsri6n5VrUJ1tJKPr4J4q7RlH+12SjW8ATd2edlsBEbB6/7t1OV4MBDleVlbtD1fu0WAlh8oWTH32HA/j74rdNfYrx52ajKlj6YHzg=,iv:XGfQmwcPihFQl00gfIph1fThktkwllhArCcDXiJ75WU=,tag:HyAPGvfNQd7gPQ2T8YHxtg==,type:comment]
#ENC[AES256_GCM,data:P6N68oDj1m90DTajDZXywCKp7LXCAyA8sRZS4lOx1nlIaoRcNSFCIgU+Nz35+4P33S9aTPR/Sq71v5eTfONVoYRRoU/fJols+D48PqwYRhQQsb5jvnBeK2gxTrbqtrm0OleHEsF5+RqgSpH1KvMBtWsSDbKlFyI29g==,iv:z5LC25MgxxxV2mdHhx5uCuuaWhAMDCw6txij2Wu40i4=,tag:vXLRdohzy5wnek/7uwQXSA==,type:comment]
#
#ENC[AES256_GCM,data:qg6GkGClvTNZti7gJOgI0UCg9407X2CHoQXp9MddwbgMpvzxv8PJKw==,iv:MDR/WwIW1jmGNkJyhUWR436Q5hcXexLjOpNkiDAqNxU=,tag:hRxEwJD8Gukd3uAXZNbWxg==,type:comment]
#ENC[AES256_GCM,data:Y+j3j+qQts7SU1bVMNa0zXdCgrWmukcsKoudsevEd8B1PQ==,iv:dVUjSQHp/d5OCGCGW6peCsGa3gJPgq7L0oMFjwZjTWQ=,tag:hUhMDu2j5/s2DKq7W8/3cQ==,type:comment]
#ENC[AES256_GCM,data:UKIDAqwLbw+P4SSPN6q/NWphro0zLPRdvNouFoszyF2OYImB,iv:WdFlXgOWMmL8gGAAoi1ipwYHfjrsk/5c4btJ6dhdm40=,tag:eldChtXp5JNg09Bh36ZbqQ==,type:comment]
wgQuickConfiguration: ENC[AES256_GCM,data:Y9bOlScRWq4p64Upnz4BX+gG/g7zBgPeJza7RwcIzKPQQlPVrW9K0/KKthogssHxp/i03vBIEZmmzUSg92DNh9uK01SDu+ypva6yHgvZwyf+jC4IouvvdJbrmRlPpS3+nbs38JUcgEBU5Z/Ytjrs6zZugzGgqaVeIvW29g0fMwINp2NET6DyW+Tv6qwaL1z3ySGlEkuLiHrZtKvZRH2uha1Ed/Ylbmhr7CKGVhVAFIGrPE1eB51qtanjjyJ0LPKiLPAl3SDljKFc6JeARsUQoLirJK6kBpZO7Y831etMTY4SDZCR0cuzcE1qzbV3mCmQUxc+3VEfb5paf5MMQEcw5g==,iv:+VDcMTpn8W98LUc0FCUq18QG1JWRg5JAJKfHkxvOVNY=,tag:n3IKzLogXK/dMdymTB8uDA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoaHdGTzFyOThYcy91S1cv
            VmdxaXFlelo5WVZ1N1hnMk1qZWxHN1NqVjEwCkJUM21MWFVsY1NVcWRFWlBLSG1t
            TFJOVjNlN09IcDFXOURUclRhOXFHcHMKLS0tIHR4b0lPMy9PU2pNY2IzTk94WHRI
            YTR5a3Q4MUgzNXdrZktYNDF6ZXlhRlEKig164sOHuE53gdWzPFkh9e2UlvbzCNM+
            NiG1YiSwkiu7pUAJvXXWtmc2DPUrjSniDBXwarjwLOEhY/6n9YqSwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w4gpvqfdw2w7ly0fjlcaddxlvt3mwd0hvp3rhvk4jtd5m2cmsp4segcmej
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSFBvQmNQa0RNM1A5UU5H
            ZGhORWdXRVNSdTJ6Uk5jMVB4eExKVXF2emxzCjVLaTZIaWtKQUF4SDQwaWFLS1VH
            Mk9nMGpsZnd6aVpWVDEzbmpHUFRwdFUKLS0tIEs0azBETWZ2U09rTFllK2ZiZ1U0
            SFRPTjRFdTIxcXZ5NjQvcVB6NFFqTjgKflbhpQOXZc1hjM77kiTcUV9Tam4QfVPn
            mLZPEykxxy13LrcUjFAzULoIypuutJuQdmEJMwZrCYPcwc330W32LQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sj3axmvypjme2f9m7csxehahj78chnek6dhrhhlv4hqjd4lgd5lq6sehmk
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQVVSUExvNHl2M2JJWlc1
            RkRPL202bkt0NU5KTW8yNmVpVHprdjZMOGw4ClpReTlBMmR1Nkd1M3JPaDNDYWNH
            bjhDRU8wQTJNTzhRNlI3R0Z4Skt0S1EKLS0tIFBDeDVTU25kWG56cWk2WXdaVDFT
            emxaMjhIRDU3QkRUNFdOSDA1cmlLRmsKzNVmNW6EZkaJbqL7/SMzbDk/vHjrTPCx
            AjH2xagzAohR1ByA+/qXGJzI3MrZHEy890xdAdRa2pBcKzpjWHWF+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1laa24tfw3yf9sms55ydw8h437h7ksyt4alwnsjg3z5569tlc0gmq2ceyvt
    lastmodified: "2026-07-31T01:23:47Z"
    mac: ENC[AES256_GCM,data:3Ka4GV9wQsV+wN/MhdPVHhEhT4UyIZkUmM15rbZKe2WPySdSrbJ0knG402fYPIYXCzITmtsztq7Vv+zo0/36HABY5nCq1v9ObLtBxnjFdvZC0OJ+sxC8z6N2O7nvI2LstwSyAandN71SOXCKum/cMWSe0QKk6E2fJzUUBVz/3L4=,iv:JJia/PSPiRzRVKUgzds1mV9swwel7Xsg2/WE+9PuHgE=,tag:WcQGfH1uqQIaUBbW1OXOPg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
