nordAccessToken: ENC[AES256_GCM,data:jcUNURJEB5hOzFZoO3ku/mAC5J+ofzNj9Dmcl5Hrr336tW+Osc5uZj5rPdVIYGj4hhQrEFyyH+PRbic1UfF0KpI=,iv:HPh3aOsv0/fHbwRVNWIJZSRZvEGP6dBkGsB2qLgPBfs=,tag:Wv9XYGA2c7QpNzLcgal84Q==,type:str]
nordUsername: ENC[AES256_GCM,data:0tPyjYsGahXT/BWOr56Jerx9I9EtwiR4,iv:fLTLDxfgyGR3/xKaT4pjoHsVnu1PJ3mm318zuNjt7Iw=,tag:jqYd2KhsVN0GWBOlcjJwgQ==,type:str]
nordPassword: ENC[AES256_GCM,data:hsj6xtSA9CdkY3ZwsrIqJcLqq5mkbkAs,iv:8DngF6vX3dfc6QJegdRJRh8tpZbaPi/pWNEPb1/SgQw=,tag:Q8aJmM3DDcH470GWRxzcdQ==,type:str]
#ENC[AES256_GCM,data:3pjFu3/N2budNqeoM+LFjVwhcoHvt912BDmvzNHEvkZ453UZY1r19CKF00Of45YsJQ==,iv:q1ynd77muxVf3I3p3lhXMg/gos1OfUuDEtx9pby3L28=,tag:X4VaSGULUiFzU7U/Jgd6Vg==,type:comment]
#ENC[AES256_GCM,data:XmUwAiQiKAIiPD/gC6rMRMkVU/6HeNKyxRB0y/0dqtojoSp/OWK7LMhXt2pxXTjLZQVG9uWi/FtZtSg7GwHZpqem8T6mqguPW5fSyuxev+Npbjt6szV42xa7zHCWgbQ5roFiYx6RYlA9rmbM+44k4pzK+fy5tTo=,iv:sHgGW5mTUtx6k+9zHeFoxVrXlMOrhb2jYwhw7z4NL94=,tag:N5zeKr+dHtrhELG1Hpq6vA==,type:comment]
#
#ENC[AES256_GCM,data:ecmdSKLWDWoq9g+opPcXGlhCSzMInu6q8p5uXTfe1UMMOk20gUH46oatnpr8y96Umxk73RVNG5q10H8iUeg0rmoJQlJ0SGaaNtPqkYJbn+60YaSTy9iGNBbZWRTufzW/4E0sM2SopJKrTtXmYidkJt+W2JIJ,iv:77HBgsgM6pXu0YR1TGZOpIpLG4gs6oT/flJrlqbXiyg=,tag:3782sFMWy7/pEMaotka6Pg==,type:comment]
#
wgQuickConfiguration: ENC[AES256_GCM,data:X5FZ5rMgXGmsqctWtqc8z3ELxSZ+d9bxjQTymLQ1wXRJbD6iO2lyStLNr3g2soBvjS8ZWU+DRkLnRjrxJoJCR5QECIv1kSBakukE9utxkavysvipd3cnUIoghCK4PTLXZlUs5wgubNqOxKMVlvAGKuIrMTHopugGHWJPVOH18mocbYz/hGy/ZpbCGmPCk5/1X6BwcAcYYunHGgoGFaUXOMR5nxMZrTXmDDDvK8C9BXgvQPXXmJNXX/e2V2ZCkV2vVOs5iD70jxUqqhyWn1Fzi0dQ7faGQSB9G1jeqF8kqg11x0PxBT1AaAy0G+lO1wtDA78HS7eP6i8BlpNlEt31rOkC,iv:AxTPHd7/Mnl6DoL/S7gA4ootsL3Wq0K4azY+mlxhQPM=,tag:GJ6fo4dn1Gds8ZVzoiYq5Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoaHdGTzFyOThYcy91S1cv
            VmdxaXFlelo5WVZ1N1hnMk1qZWxHN1NqVjEwCkJUM21MWFVsY1NVcWRFWlBLSG1t
            TFJOVjNlN09IcDFXOURUclRhOXFHcHMKLS0tIHR4b0lPMy9PU2pNY2IzTk94WHRI
            YTR5a3Q4MUgzNXdrZktYNDF6ZXlhRlEKig164sOHuE53gdWzPFkh9e2UlvbzCNM+
            NiG1YiSwkiu7pUAJvXXWtmc2DPUrjSniDBXwarjwLOEhY/6n9YqSwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w4gpvqfdw2w7ly0fjlcaddxlvt3mwd0hvp3rhvk4jtd5m2cmsp4segcmej
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSFBvQmNQa0RNM1A5UU5H
            ZGhORWdXRVNSdTJ6Uk5jMVB4eExKVXF2emxzCjVLaTZIaWtKQUF4SDQwaWFLS1VH
            Mk9nMGpsZnd6aVpWVDEzbmpHUFRwdFUKLS0tIEs0azBETWZ2U09rTFllK2ZiZ1U0
            SFRPTjRFdTIxcXZ5NjQvcVB6NFFqTjgKflbhpQOXZc1hjM77kiTcUV9Tam4QfVPn
            mLZPEykxxy13LrcUjFAzULoIypuutJuQdmEJMwZrCYPcwc330W32LQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sj3axmvypjme2f9m7csxehahj78chnek6dhrhhlv4hqjd4lgd5lq6sehmk
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQVVSUExvNHl2M2JJWlc1
            RkRPL202bkt0NU5KTW8yNmVpVHprdjZMOGw4ClpReTlBMmR1Nkd1M3JPaDNDYWNH
            bjhDRU8wQTJNTzhRNlI3R0Z4Skt0S1EKLS0tIFBDeDVTU25kWG56cWk2WXdaVDFT
            emxaMjhIRDU3QkRUNFdOSDA1cmlLRmsKzNVmNW6EZkaJbqL7/SMzbDk/vHjrTPCx
            AjH2xagzAohR1ByA+/qXGJzI3MrZHEy890xdAdRa2pBcKzpjWHWF+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1laa24tfw3yf9sms55ydw8h437h7ksyt4alwnsjg3z5569tlc0gmq2ceyvt
    lastmodified: "2026-07-24T16:01:28Z"
    mac: ENC[AES256_GCM,data:x6kNem6xT55yI2wupaZxoz7K3Ou72mOMea3X15y1cqZmlgq3jQ2SxAEVr1Wmi4Z1XmFOIUAyJY7ySjcgxFX2k7ZtvYn5zZjE2783fIYYFxsnP85CPGqBEZit5Kfjjnt/4yuBPsaLERmuPmVd5+99gF0iQzdWNGmHuyGJ9sJ1+yI=,iv:Y2nuMsOqeHaNkUIvS8EKB1JNS6MNIciL2jsA4B11RKQ=,tag:mCdTK2gpAw0QfsoMn/Q7RA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
